spring.application.name=nvs_bansach
# port: 8080
server.port=8080
# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/bansach
spring.datasource.username=root
spring.datasource.password=okkaio12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate settings/JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Trong src/main/resources/application.properties

# Chu?i bí m?t ph?i dài t?i thi?u 256 bits (32 byte) và ???c mã hóa Base64
# Chu?i d??i ?ây ?ã ???c Base64 encode
application.security.jwt.secret-key=MzU3ODMxMDMyODc5NTU1MzY0MTc3MjY5MjI1NTc0NTI2NTUxODI5Mzk4ODQ1NzYzOTU1NjI3Njg1NjU1NzgxMzU4MzU=

# Th?i gian h?t h?n c?a token (86400000 ms = 24 gi?)
application.security.jwt.expiration=86400000